name: Python Package CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and setup Python
        run: |
          pip install uv
          uv python --version ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync

      - name: Run tests
        run: pytest

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Build package
        run: hatch build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
