name: Python Package CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: |
          pip install uv
          uv venv --python ${{ matrix.python-version }}
          uv sync  --group dev
          source  .venv/bin/activate
          uv pip install  .
          pytest

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build
        run: |
          pip install uv
          uv sync  --group dev
          source  .venv/bin/activate
          uv pip install  .
          hatch build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
